name: Python Lint CI

on:
  push:
    branches:
      [main, trunk]
  pull_request:
    branches:
      [main, trunk]

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Python Set up
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-pyproject black isort

      - name: Format code with isort
        run: isort app rosemary core

      - name: Format code with black
        run: black app rosemary core

      - name: Commit and push formatted code
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "style: auto-format code with black and isort" || true
          git push || true

      - name: Lint with flake8
        run: flake8 app rosemary core

      - name: Check import order with isort
        run: isort --check-only app rosemary core

      - name: Check formatting with black
        run: black --check app rosemary core